version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root                    # Your PostgreSQL username
      POSTGRES_PASSWORD: 12345678             # Your PostgreSQL password
      POSTGRES_DB: employes_bd                 # Name of the database to create
    ports:
      - "5432:5432"                            # Expose PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/data        # Persist data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]  # Check if PostgreSQL is ready
      interval: 5s                              # Interval between health checks
      timeout: 2s                               # Timeout for each check
      retries: 5                                 # Number of retries before marking as unhealthy

  backend:
    build:
      context: .                               # Context for building the backend image
      dockerfile: Dockerfile                   # Path to your Go backend Dockerfile
    environment:
      DB_HOST: db                              # Service name for the database
      DB_PORT: 5432                            # Default PostgreSQL port
      DB_USER: root                            # Same as above
      DB_PASSWORD: 12345678                    # Same as above
      DB_NAME: employes_bd                     # Same as above
    ports:
      - "8080:8080"                            # Expose your backend port
    depends_on:
      db:
        condition: service_healthy             # Wait for db to be healthy before starting

volumes:
  pgdata: {} 

